### ISSUE TITLE
Installation: "The executable of SublimeOverlay"

### ISSUE THREAD

**Issue by mrhaw** [mikadev001/SublimeText-Overlay#11]
I have spent 15 min trying to understand this: "The executable of SublimeOverlay"

Any reference links to learn what a Sublime executable file is? Do I open the file or use preferences > Browse packages!?

I realize you have spent time coding this and am thankful for you sharing it to the world.

**Comment by nicosli** [comment]
i have the same problem... i don't understand

**Comment by mrhaw** [comment]
I downloaded the wrong thing! :)

Click SublimeOverlay 1.3.2 :arrow_down:
on this page: https://github.com/mikadev001/SublimeText-Overlay/releases/tag/1.3.2

That has an .exe :+1:
