### ISSUE TITLE
Bug when unsaved file is exists and try to exit overlay

### ISSUE THREAD

**Issue by littmus** [mikadev001/SublimeText-Overlay#12]
![image](https://cloud.githubusercontent.com/assets/1590516/13524373/2b05faf4-e23e-11e5-9ff1-80249db73ed3.png)
If I select cancel to close file, overlay bar disappear.

**Comment by mikadev001** [comment]
The save file dialog on exit never showed up on my computer. What version of Sublime Text are you using?

**Comment by mikadev001** [comment]
Figured it out. This happens when `hot_fix` setting is set to false. Working on it now
