### ISSUE TITLE
How To Install SublimeText-Overlay?

### ISSUE THREAD

**Issue by SanjayBanjade** [mikadev001/SublimeText-Overlay#23]
I am confused. I am not able to install this plugin. Please help me. Also please improve the documentation.

**Comment by Bernardi23** [comment]
Same here. Anyone?

**Comment by SanjayBanjade** [comment]
Hi @Bernardi23 ! I figured out the solution a while ago. Here's how:

1. Goto this link and download the file: https://github.com/mikadev001/SublimeText-Overlay/files/164320/SublimeOverlay.zip
2. Extract it and you should see the .exe file!
3. Now open Sublime Text & then open the .exe file you downloaded!

That's it

**Comment by SanjayBanjade** [comment]
@Bernardi23 See Usage section of the documentation,

**Comment by Bernardi23** [comment]
Thanks for the reply, once again. I'm sorry, but I couldn't figure it out.
It tells me to create a shortcut. But a shortcut of what? Sublime or the
overlay? Also passing arguments for a shortcut?
Sorry if this is obvious.

**Comment by SanjayBanjade** [comment]
@Bernardi23 Here are the steps:
1. Create a shortcut of SublimeOverlay.exe
2. Right click on that shortcut and look for Target field under Shortcut option.
3. Add (don't remove the existing line) this line at last in the target field: `--startsublime --sublime-path="C:\Program Files\Sublime Text 3\sublime_text.exe"`. Note: `C:\Program Files\Sublime Text 3\` will be the installation directory of your Sublime Text!

Done :)

**Comment by Bernardi23** [comment]
Thanks!
