### ISSUE TITLE
a bug when using strokesplus to minimize the window

### ISSUE THREAD

**Issue by yuuuxt** [mikadev001/SublimeText-Overlay#9]
![image 001_0212_0106](https://cloud.githubusercontent.com/assets/3153534/12995093/14c0c19a-d125-11e5-96d3-9b40167fb1c2.png)

**Comment by mikadev001** [comment]
Fixed, checkout [1.3.2](https://github.com/mikadev001/SublimeText-Overlay/releases/tag/1.3.2)
